// Generated by rstantools.  Do not edit by hand.

/*
    BayesGrowth is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    BayesGrowth is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with BayesGrowth.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0
#include <stan/model/model_header.hpp>
namespace model_Schnute_stan_model_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_Schnute_stan_model");
    reader.add_event(94, 92, "end", "model_Schnute_stan_model");
    return reader;
}
#include <stan_meta_header.hpp>
class model_Schnute_stan_model
  : public stan::model::model_base_crtp<model_Schnute_stan_model> {
private:
        int n;
        vector_d Age;
        vector_d Length;
        double tau1;
        double tau2;
        vector_d priors;
        vector_d priors_se;
public:
    model_Schnute_stan_model(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_Schnute_stan_model(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_Schnute_stan_model_namespace::model_Schnute_stan_model";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "n", "int", context__.to_vec());
            n = int(0);
            vals_i__ = context__.vals_i("n");
            pos__ = 0;
            n = vals_i__[pos__++];
            check_greater_or_equal(function__, "n", n, 1);
            current_statement_begin__ = 10;
            validate_non_negative_index("Age", "n", n);
            context__.validate_dims("data initialization", "Age", "vector_d", context__.to_vec(n));
            Age = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("Age");
            pos__ = 0;
            size_t Age_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < Age_j_1_max__; ++j_1__) {
                Age(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "Age", Age, 0);
            current_statement_begin__ = 11;
            validate_non_negative_index("Length", "n", n);
            context__.validate_dims("data initialization", "Length", "vector_d", context__.to_vec(n));
            Length = Eigen::Matrix<double, Eigen::Dynamic, 1>(n);
            vals_r__ = context__.vals_r("Length");
            pos__ = 0;
            size_t Length_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < Length_j_1_max__; ++j_1__) {
                Length(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "Length", Length, 0);
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "tau1", "double", context__.to_vec());
            tau1 = double(0);
            vals_r__ = context__.vals_r("tau1");
            pos__ = 0;
            tau1 = vals_r__[pos__++];
            check_greater_or_equal(function__, "tau1", tau1, 0);
            current_statement_begin__ = 15;
            context__.validate_dims("data initialization", "tau2", "double", context__.to_vec());
            tau2 = double(0);
            vals_r__ = context__.vals_r("tau2");
            pos__ = 0;
            tau2 = vals_r__[pos__++];
            check_greater_or_equal(function__, "tau2", tau2, 0);
            current_statement_begin__ = 17;
            validate_non_negative_index("priors", "5", 5);
            context__.validate_dims("data initialization", "priors", "vector_d", context__.to_vec(5));
            priors = Eigen::Matrix<double, Eigen::Dynamic, 1>(5);
            vals_r__ = context__.vals_r("priors");
            pos__ = 0;
            size_t priors_j_1_max__ = 5;
            for (size_t j_1__ = 0; j_1__ < priors_j_1_max__; ++j_1__) {
                priors(j_1__) = vals_r__[pos__++];
            }
            current_statement_begin__ = 18;
            validate_non_negative_index("priors_se", "2", 2);
            context__.validate_dims("data initialization", "priors_se", "vector_d", context__.to_vec(2));
            priors_se = Eigen::Matrix<double, Eigen::Dynamic, 1>(2);
            vals_r__ = context__.vals_r("priors_se");
            pos__ = 0;
            size_t priors_se_j_1_max__ = 2;
            for (size_t j_1__ = 0; j_1__ < priors_se_j_1_max__; ++j_1__) {
                priors_se(j_1__) = vals_r__[pos__++];
            }
            check_greater_or_equal(function__, "priors_se", priors_se, 0);
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 24;
            num_params_r__ += 1;
            current_statement_begin__ = 25;
            num_params_r__ += 1;
            current_statement_begin__ = 27;
            num_params_r__ += 1;
            current_statement_begin__ = 28;
            num_params_r__ += 1;
            current_statement_begin__ = 31;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_Schnute_stan_model() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 24;
        if (!(context__.contains_r("L1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable L1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("L1");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "L1", "double", context__.to_vec());
        double L1(0);
        L1 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, L1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable L1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 25;
        if (!(context__.contains_r("L2")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable L2 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("L2");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "L2", "double", context__.to_vec());
        double L2(0);
        L2 = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, L2);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable L2: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 27;
        if (!(context__.contains_r("a")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable a missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("a");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "a", "double", context__.to_vec());
        double a(0);
        a = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(a);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable a: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 28;
        if (!(context__.contains_r("b")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable b missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("b");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "b", "double", context__.to_vec());
        double b(0);
        b = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(b);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable b: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 31;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 24;
            local_scalar_t__ L1;
            (void) L1;  // dummy to suppress unused var warning
            if (jacobian__)
                L1 = in__.scalar_lb_constrain(0, lp__);
            else
                L1 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 25;
            local_scalar_t__ L2;
            (void) L2;  // dummy to suppress unused var warning
            if (jacobian__)
                L2 = in__.scalar_lb_constrain(0, lp__);
            else
                L2 = in__.scalar_lb_constrain(0);
            current_statement_begin__ = 27;
            local_scalar_t__ a;
            (void) a;  // dummy to suppress unused var warning
            if (jacobian__)
                a = in__.scalar_constrain(lp__);
            else
                a = in__.scalar_constrain();
            current_statement_begin__ = 28;
            local_scalar_t__ b;
            (void) b;  // dummy to suppress unused var warning
            if (jacobian__)
                b = in__.scalar_constrain(lp__);
            else
                b = in__.scalar_constrain();
            current_statement_begin__ = 31;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            // model body
            {
            current_statement_begin__ = 36;
            validate_non_negative_index("PredL", "n", n);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> PredL(n);
            stan::math::initialize(PredL, DUMMY_VAR__);
            stan::math::fill(PredL, DUMMY_VAR__);
            current_statement_begin__ = 39;
            lp_accum__.add(normal_log<propto__>(L2, get_base1(priors, 1, "priors", 1), get_base1(priors_se, 1, "priors_se", 1)));
            current_statement_begin__ = 40;
            lp_accum__.add(normal_log<propto__>(L1, get_base1(priors, 2, "priors", 1), get_base1(priors_se, 2, "priors_se", 1)));
            current_statement_begin__ = 42;
            lp_accum__.add(uniform_log<propto__>(a, 0, get_base1(priors, 3, "priors", 1)));
            current_statement_begin__ = 43;
            lp_accum__.add(uniform_log<propto__>(b, -(25), get_base1(priors, 4, "priors", 1)));
            current_statement_begin__ = 45;
            lp_accum__.add(uniform_log<propto__>(sigma, 0, get_base1(priors, 5, "priors", 1)));
            current_statement_begin__ = 49;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 52;
                if (as_bool((primitive_value(logical_neq(a, 0)) && primitive_value(logical_neq(b, 0))))) {
                    current_statement_begin__ = 53;
                    stan::model::assign(PredL, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                pow((pow(L1, b) + (((pow(L2, b) - pow(L1, b)) * (1 - stan::math::exp((-(a) * (get_base1(Age, i, "Age", 1) - tau1))))) / (1 - stan::math::exp((-(a) * (tau2 - tau1)))))), (1 / b)), 
                                "assigning variable PredL");
                } else if (as_bool((primitive_value(logical_neq(a, 0)) && primitive_value(logical_eq(b, 0))))) {
                    current_statement_begin__ = 56;
                    stan::model::assign(PredL, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (L1 * stan::math::exp(((stan::math::log((L2 / L1)) * (1 - stan::math::exp((-(a) * (get_base1(Age, i, "Age", 1) - tau1))))) / (1 - stan::math::exp((-(a) * (tau2 - tau1))))))), 
                                "assigning variable PredL");
                } else if (as_bool((primitive_value(logical_eq(a, 0)) && primitive_value(logical_neq(b, 0))))) {
                    current_statement_begin__ = 59;
                    stan::model::assign(PredL, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                pow((pow(L1, b) + (((pow(L2, b) - pow(L1, b)) * (get_base1(Age, i, "Age", 1) - tau1)) / (tau2 - tau1))), (1 / b)), 
                                "assigning variable PredL");
                } else {
                    current_statement_begin__ = 61;
                    stan::model::assign(PredL, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (L1 * stan::math::exp(((stan::math::log((L2 / L1)) * (get_base1(Age, i, "Age", 1) - tau1)) / (tau2 - tau1)))), 
                                "assigning variable PredL");
                }
                current_statement_begin__ = 64;
                lp_accum__.add(normal_log(get_base1(Length, i, "Length", 1), get_base1(PredL, i, "PredL", 1), sigma));
            }
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("L1");
        names__.push_back("L2");
        names__.push_back("a");
        names__.push_back("b");
        names__.push_back("sigma");
        names__.push_back("log_lik");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_Schnute_stan_model_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double L1 = in__.scalar_lb_constrain(0);
        vars__.push_back(L1);
        double L2 = in__.scalar_lb_constrain(0);
        vars__.push_back(L2);
        double a = in__.scalar_constrain();
        vars__.push_back(a);
        double b = in__.scalar_constrain();
        vars__.push_back(b);
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            if (!include_gqs__ && !include_tparams__) return;
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 73;
            validate_non_negative_index("log_lik", "n", n);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(n);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 75;
            for (int i = 1; i <= n; ++i) {
                current_statement_begin__ = 78;
                if (as_bool((primitive_value(logical_neq(a, 0)) && primitive_value(logical_neq(b, 0))))) {
                    current_statement_begin__ = 79;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                normal_log(get_base1(Length, i, "Length", 1), pow((pow(L1, b) + (((pow(L2, b) - pow(L1, b)) * (1 - stan::math::exp((-(a) * (get_base1(Age, i, "Age", 1) - tau1))))) / (1 - stan::math::exp((-(a) * (tau2 - tau1)))))), (1 / b)), sigma), 
                                "assigning variable log_lik");
                } else if (as_bool((primitive_value(logical_neq(a, 0)) && primitive_value(logical_eq(b, 0))))) {
                    current_statement_begin__ = 82;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                normal_log(get_base1(Length, i, "Length", 1), (L1 * stan::math::exp(((stan::math::log((L2 / L1)) * (1 - stan::math::exp((-(a) * (get_base1(Age, i, "Age", 1) - tau1))))) / (1 - stan::math::exp((-(a) * (tau2 - tau1))))))), sigma), 
                                "assigning variable log_lik");
                } else if (as_bool((primitive_value(logical_eq(a, 0)) && primitive_value(logical_neq(b, 0))))) {
                    current_statement_begin__ = 85;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                normal_log(get_base1(Length, i, "Length", 1), pow((pow(L1, b) + (((pow(L2, b) - pow(L1, b)) * (get_base1(Age, i, "Age", 1) - tau1)) / (tau2 - tau1))), (1 / b)), sigma), 
                                "assigning variable log_lik");
                } else {
                    current_statement_begin__ = 87;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                normal_log(get_base1(Length, i, "Length", 1), (L1 * stan::math::exp(((stan::math::log((L2 / L1)) * (get_base1(Age, i, "Age", 1) - tau1)) / (tau2 - tau1)))), sigma), 
                                "assigning variable log_lik");
                }
            }
            // validate, write generated quantities
            current_statement_begin__ = 73;
            size_t log_lik_j_1_max__ = n;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    std::string model_name() const {
        return "model_Schnute_stan_model";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "L1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "L2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "L1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "L2";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "a";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "b";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
        }
        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = n;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_Schnute_stan_model_namespace::model_Schnute_stan_model stan_model;
#ifndef USING_R
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
#endif
#endif
